inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  UseCache: false

Layout/LineLength:
  Enabled: true
  # When this is commented out, `Layout/LineLength` triggers on packs/my_pack/app/models/my_file.rb
  Include:
    - 'packs/**/*.rb'
